Encoder:
  id: "ID"
  encoder_name: "Модель энкодера"
  id_company: "Компания-производитель"
  id_type_encoder: "Тип энкодера"
  shaft_diameter: "Диаметр вала, мм"
  rotor_breakway_torque: "Момент ротора, Нм"
  rotor_moment_of_inertia: "Момент инерции ротора, кг·м²"
  maximum_rotation_speed: "Максимальная частота вращения, об/мин"
  supply_voltage: "Напряжение питания, В"
  lines_count: "Разрешающая способность"
  weight: "Масса, г"
  drawing: "Чертеж"
  price: "Цена, руб"

EngineDC:
  id: "ID"
  model: "Модель двигателя"
  p_nom: "Pном., Вт"
  m_nom: "Mном., Нм"
  type_id: "Тип двигателя"
  n_nom: "Частота вращения, об/мин"
  u_nom: "Uном., В"
  i_nom: "Iном., А"
  r_nom: "Rя., Ом"
  j_nom: "Момент инерции ротора, кг·м²"
  m: "Масса, г"
  max_current: "Макс. ток, А"
  price: "Цена, руб"
  drawing: "Чертеж"
  company: "Компания-производитель"
  l_a: "Индуктивность якоря, Гн"

Gear:
  id: "ID"
  gear_name: "Модель редуктора"
  gear_company: "Компания-производитель"
  gear_type: "Тип редуктора"
  i: "Передаточное отношение"
  speed_norm: "Частота вращения на выходе, об/мин"
  c: "Жесткость, Нм/рад"
  clearance: "Люфт, рад"
  torque_nom: "Номинальный момент, Нм"
  inertial_torque: "Момент инерции, кг·м²"
  mass: "Масса, г"
  price: "Цена, руб"
  drawing: "Чертеж"
  efficiency: "КПД"

Result:
  id: "ID"
  id_engine: "ID двигателя"
  id_gear: "ID редуктора"
  id_encoder: "ID энкодера"
  id_source_data: "ID исходных данных"
  id_coef_regulators: "ID коэффициентов регуляторов"
  id_utils: "ID справочных данных"

SourceData:
  id: "ID"
  max_speed: "Макс. скорость вращения, рад/с"
  max_acc: "Макс. ускорение, рад/с²"
  max_speed_work: "Макс. рабочая скорость, рад/с"
  acc_duration: "Длительность разгона до максимальной скорости, с"
  rel_duration: "Относительная длительность переброски в рабочем цикле, с"
  max_torque: "Макс. момент, Нм"
  max_intertia_torque: "Макс. момент инерции, кг·м²"
  max_error: "Допустимая ошибка, рад"
  overshoot: "Макс. перерегулирование, %"
  transition_time: "Время переходного процесса, с"

CoefRegulators:
  id: "ID"
  k_dc: "Коэффициент обратной связи по току"
  k_c: "Коэффициент П составляющей регулятора тока"
  k_ci: "Коэффициент И составляющей регулятора тока"
  k_ds: "Коэффициент обратной связи по скорости"
  k_s: "Коэффициент П составляющей регулятора скорости"
  k_si: "Коэффициент И составляющей регулятора скорости"
  k_da: "Коэффициент датчика положения"
  k_a: "Коэффициент П составляющей регулятора положения"
  k_ai: "Коэффициент И составляющей регулятора положения"
  k_pwm: "Коэффициент ШИМ"
  T_pwm: "Некомпенсируемая постоянная времени, с"
  k_feedforward: "Коэффициент упреждающего воздействия"
  #k_correct: "Коэффициент корректирующего алгоритма"

Utils:
  id: "ID"
  A_e: "Амплитуда эквивалентного гаромонического воздействия, рад"
  omega_e: "Частота эквивалентного гаромонического воздействия, рад/с"
  dyn_error: "Динамическая ошибка, рад"
  stat_error: "Статическая ошибка, рад"
