function [Optimized_DesignVars,Info] = responseOptimization_lab12_a(DesignVars)
%RESPONSEOPTIMIZATION_LAB12_A
%
% Solve a design optimization problem for the lab12_a model.
%
% The function returns optimized parameter values, Optimized_DesignVars,
% and optimization termination information, Info.
%
% The input argument, DesignVars, defines the model parameters to optimize,
% if omitted the parameters specified in the function body are optimized.
%
% Modify the function to include or exclude new design requirements, or
% to change the optimization options.
%
% Auto-generated by SDOTOOL on 19-Apr-2026 14:09:10.
%

%% Open the model.
open_system('lab12_a')

%% Specify Design Variables
%
% Specify model parameters as design variables to optimize.
if nargin < 1 || isempty(DesignVars)
    DesignVars = sdo.getParameterFromModel('lab12_a','kp');
    DesignVars(1).Minimum = 0;
end

%% Specify Design Requirements
%
% Specify design requirements to satisfy during optimization.
Requirements = struct;
Requirements.StepRespEnvelope = sdo.requirements.StepResponseEnvelope(...
    'FinalValue', 10, ...
    'PercentOvershoot', 5, ...
    'PercentSettling', 0.9999999999999964, ...
    'RiseTime', 0.1, ...
    'SettlingTime', 0.11);

%% Simulation Definition
%
% Specify model signals to log during model simulation.
Simulator = sdo.SimulationTest('lab12_a');

Sig_Info = Simulink.SimulationData.SignalLoggingInfo;
Sig_Info.BlockPath = 'lab12_a/backlash';
Sig_Info.LoggingInfo.LoggingName = 'Sig';
Sig_Info.LoggingInfo.NameMode = 1;

Simulator.LoggingInfo.Signals = Sig_Info;

%% Configure setup and restoration of simulator
%

% Setup simulator
Simulator = setup(Simulator, 'FastRestart', 'off');

% Add Cleanup tasks to restore any changes after completion/termination.
% Use an anonymous function with no arguments that calls the restore method.
SimulatorCleanup = onCleanup(@() restore(Simulator));

%% Create Optimization Objective Function
%
% Create a function that is called at each optimization iteration
% to evaluate the design requirements.
%
% Use an anonymous function with one argument that calls lab12_a_optFcn.
optimfcn = @(P) lab12_a_optFcn(P,Simulator,Requirements);

%% Optimization Options
%
% Specify optimization options.
Options = sdo.OptimizeOptions;
Options.Method = 'paretosearch';
Options.OptimizedModel = Simulator;

%% Optimize the Design
%
% Call sdo.optimize with the objective function handle, parameters to
% optimize, and options.
[Optimized_DesignVars,Info] = sdo.optimize(optimfcn,DesignVars,Options);
end

function Vals = lab12_a_optFcn(P,Simulator,Requirements)
%LAB12_A_OPTFCN
%
% Function called at each iteration of the optimization problem.
%
% The function is called with a set of parameter values, P, and returns
% the objective value and constraint violations, Vals, to the optimization
% solver.
%
% See the sdoExampleCostFunction function and sdo.optimize for a more
% detailed description of the function signature.
%

%% Model Evaluation

% Simulate the model.
Simulator.Parameters = P;
Simulator = sim(Simulator);

% Retrieve logged signal data.
SimLog = find(Simulator.LoggedData,get_param('lab12_a','SignalLoggingName'));
Sig_Log = find(SimLog,'Sig');

% Evaluate the design requirements.
Cleq_StepRespEnvelope = evalRequirement(Requirements.StepRespEnvelope,Sig_Log.Values);

%% Return Values.
%
% Collect the evaluated design requirement values in a structure to
% return to the optimization solver.
Vals.Cleq = Cleq_StepRespEnvelope(:);
end
